---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:
    - name: no mlag
      eos_config:
        lines:
          - configure

          - interface Ethernet 1-2
          - shutdown
          - exit
          - mlag configuration
          - shutdown


      when: ansible_network_os == 'eos'




