---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:
    - name: Configuration Du vlan 12
      eos_config:
        lines:
          - configure
          - vlan 12
          - interface vlan 12
          - ip address 172.16.112.3/24
          - ip virtual-router address 172.16.112.1

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 2
      eos_config:
        lines:
          - configure
          - interface Ethernet 2
          - description LEAF5
          - switchport mode trunk
          - channel-group 12 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 3
      eos_config:
        lines:
          - configure
          - interface Ethernet 3
          - description LEAF6
          - switchport mode trunk
          - channel-group 12 mode active

      when: ansible_network_os == 'eos'
      
    - name: Configuration Port Channel 12
      eos_config:
        lines:
          - configure

          - interface port-channel 4
          - description MLAG-LEAF5&6
          - switchport mode trunk
          - mlag 12

      when: ansible_network_os == 'eos'

      

   
   
