---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"


  tasks:
    - name: Startup config initilisation
      eos_config:
        lines:
          - configure
          - copy file:/home/scp/Leaf-4.txt startup-config

      when: ansible_network_os == 'eos'

