---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:


    - name: Configuration Interface Loopback0
      eos_config:
        lines:
          - configure

          - ip routing

          - interface loopback 0
          - ip address 172.16.0.13/32

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - no switchport
          - no switchport mode trunk
          - no channel-group 34 

          - ip address 172.16.200.10/30

      when: ansible_network_os == 'eos'


    - name: Configuration Interface Ethernet 7
      eos_config:
        lines:
          - configure



          - interface Ethernet 7
          - no switchport
          - no switchport mode trunk
          - no channel-group 34 

          - ip address 172.16.200.26/30

      when: ansible_network_os == 'eos'



    - name: Configuration Interface Vlan 3
      eos_config:
        lines:
          - configure

          - interface vlan3
          - ip address 172.16.116.2/24
          - ip virtual-router address 172.16.116.1

      when: ansible_network_os == 'eos'

    - name: Configuration MAC virtual routeur
      eos_config:
        lines:
          - configure

          - ip virtual-router mac-address 00:1c:73:00:00:34

      when: ansible_network_os == 'eos'


    - name: Configuration Routeur BGP
      eos_config:
        lines:
          - configure

          - router bgp 65002
          - router-id 172.16.0.13
          - maximum-paths 4 ecmp 4
          - neighbor 172.16.34.2 remote-as 65002
          - neighbor 172.16.34.2 next-hop-self
          - neighbor 172.16.200.9 remote-as 65000
          - neighbor 172.16.200.9 maximum-routes 12000
          - neighbor 172.16.200.25 remote-as 65000
          - neighbor 172.16.200.25 maximum-routes 12000
          - network 172.16.0.13/32
          - network 172.16.1.34/32
          - network 172.16.116.0/24



      when: ansible_network_os == 'eos'


