---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:

    - name: Configuration Interface Loopback0
      eos_config:
        lines:
          - configure

          - ip routing

          - interface loopback 0
          - ip address 172.16.0.4/32

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 5
      eos_config:
        lines:
          - configure

          - interface Ethernet 5
          - no switchport
          - no switchport mode trunk
          - no channel-group 56

          - ip address 172.16.200.49/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - no switchport
          - no switchport mode trunk
          - no channel-group 56
          - ip address 172.16.200.53/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 7
      eos_config:
        lines:
          - configure

          - interface Ethernet 7
          - no switchport
          - no switchport mode trunk
          - no channel-group 78
          - ip address 172.16.200.57/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 8
      eos_config:
        lines:
          - configure

          - interface Ethernet 8
          - no switchport
          - no switchport mode trunk
          - no channel-group 78
          - ip address 172.16.200.61/30

      when: ansible_network_os == 'eos'

    - name: Configuration Routeur BGP
      eos_config:
        lines:
          - configure

          - router bgp 65003
          - router-id 172.16.0.4
          - maximum-paths 4 ecmp 4
          - neighbor 172.16.200.50 remote-as 65004
          - neighbor 172.16.200.50 send-community extended
          - neighbor 172.16.200.50 maximum-routes 12000
          - neighbor 172.16.200.54 remote-as 65004
          - neighbor 172.16.200.54 send-community extended
          - neighbor 172.16.200.54 maximum-routes 12000
          - neighbor 172.16.200.58 remote-as 65005
          - neighbor 172.16.200.58 send-community extended
          - neighbor 172.16.200.58 maximum-routes 12000
          - neighbor 172.16.200.62 remote-as 65005
          - neighbor 172.16.200.62 send-community extended
          - neighbor 172.16.200.62 maximum-routes 12000
          - network 172.16.0.4/32



      when: ansible_network_os == 'eos'


