---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"
    mlag_peer_link_description: "MLAG PEER LINK - SPINE-2"
    mlag_peer: "MLAGPEER"
    spine: "SPINE-2"

  tasks:
    - name: Configuration Du vlan 4094
      eos_config:
        lines:
          - configure
          - vlan 3
          - vlan 34
          - vlan 12
          - vlan 4094
          - trunk group "{{ mlag_peer }}"

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 1
      eos_config:
        lines:
          - configure

          - interface Ethernet 1
          - description "{{ mlag_peer_link_description }}"
          - channel-group 10 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 2
      eos_config:
        lines:
          - configure

          - interface Ethernet 2
          - description "{{ mlag_peer_link_description }}"
          - channel-group 10 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Port Channel 10
      eos_config:
        lines:
          - configure

          - interface port-channel 10
          - description "{{ mlag_peer_link_description }}"
          - switchport mode trunk
          - switchport trunk group "{{ mlag_peer }}"
          - no spanning-tree vlan-id 4094

      when: ansible_network_os == 'eos'


    - name: Configuration IP addresse sur le Port Channel 10 "{{ spine }}"
      eos_config:
        lines:
          - configure
          - interface vlan 4094
          - description MLAG PEER LINK "{{ spine }}"
          - ip address 172.16.5.2/24

      when: ansible_network_os == 'eos'

    - name: Configuration du MLAG peer link
      eos_config:
        lines:
          - configure
          - mlag configuration
          - domain-id MLAG30
          - local-interface Vlan4094
          - peer-address 172.16.5.1
          - peer-link Port-Channel10

      when: ansible_network_os == 'eos'


    - name: Configuration Interface Ethernet 3
      eos_config:
        lines:
          - configure

          - interface Ethernet 3
          - description LEAF 4
          - channel-group 34 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 4
      eos_config:
        lines:
          - configure

          - interface Ethernet 4
          - description LEAF 3
          - channel-group 34 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 5
      eos_config:
        lines:
          - configure

          - interface Ethernet 5
          - description LEAF 2
          - channel-group 12 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - description LEAF 1
          - channel-group 12 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Port Channel 34
      eos_config:
        lines:
          - configure

          - interface port-channel 34
          - description MLAG - LEAF3 & 4
          - switchport mode trunk
          - mlag 34

      when: ansible_network_os == 'eos'

    - name: Configuration Port Channel 12
      eos_config:
        lines:
          - configure

          - interface port-channel 12
          - description MLAG - LEAF1 & 2
          - switchport mode trunk
          - mlag 12

      when: ansible_network_os == 'eos'



