---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"
    mlag_peer_link_description: "MLAG PEER LINK - LEAF-7"
    mlag_peer: "MLAGPEER"
    leaf: "LEAF-7"

  tasks:
    - name: Configuration Du vlan 4094
      eos_config:
        lines:
          - configure
          - vlan 3
          - vlan 4094
          - trunk group "{{ mlag_peer }}"

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 1
      eos_config:
        lines:
          - configure

          - interface Ethernet 1
          - description "{{ mlag_peer_link_description }}"
          - channel-group 10 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 2
      eos_config:
        lines:
          - configure

          - interface Ethernet 2
          - description "{{ mlag_peer_link_description }}"
          - channel-group 10 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Port Channel 10
      eos_config:
        lines:
          - configure

          - interface port-channel 10
          - description "{{ mlag_peer_link_description }}"
          - switchport mode trunk
          - switchport trunk group "{{ mlag_peer }}"
          - no spanning-tree vlan-id 4094

      when: ansible_network_os == 'eos'


    - name: Configuration IP addresse sur le Port Channel 10 "{{ leaf }}"
      eos_config:
        lines:
          - configure
          - interface vlan 4094
          - description MLAG PEER LINK "{{ leaf }}"
          - ip address 172.16.78.1/24

      when: ansible_network_os == 'eos'

    - name: Configuration du MLAG peer link
      eos_config:
        lines:
          - configure
          - mlag configuration
          - domain-id MLAG78
          - local-interface Vlan4094
          - peer-address 172.16.78.2
          - peer-link Port-Channel10

      when: ansible_network_os == 'eos'


    - name: Configuration Interface Ethernet 3
      eos_config:
        lines:
          - configure

          - interface Ethernet 3
          - description HOST4
          - channel-group 3 mode active

      when: ansible_network_os == 'eos'
      
    - name: Configuration Port Channel 3
      eos_config:
        lines:
          - configure

          - interface port-channel 3
          - description MLAG - HOST4
          - switchport access vlan 3
          - mlag 3

      when: ansible_network_os == 'eos'



    - name: Configuration Interface Ethernet 7
      eos_config:
        lines:
          - configure

          - interface Ethernet 7
          - description SPINE 4
          - channel-group 78 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - description SPINE 3
          - channel-group 78 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Port Channel 78
      eos_config:
        lines:
          - configure

          - interface port-channel 78
          - description MLAG - SPINE3 & 4
          - switchport mode trunk
          - mlag 78

      when: ansible_network_os == 'eos'




