---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:


    - name: Configuration Interface Loopback0
      eos_config:
        lines:
          - configure

          - ip routing

          - interface loopback 0
          - ip address 172.16.0.1/32

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 8
      eos_config:
        lines:
          - configure



          - interface Ethernet 8
          - no switchport
          - no switchport mode trunk
          - no channel-group 12 

          - ip address 172.16.200.1/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 7
      eos_config:
        lines:
          - configure

          - interface Ethernet 7
          - no switchport
          - no switchport mode trunk
          - no channel-group 12 

          - ip address 172.16.200.5/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - no switchport
          - no switchport mode trunk
          - no channel-group 34

          - ip address 172.16.200.9/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 5
      eos_config:
        lines:
          - configure

          - interface Ethernet 5

          - no switchport
          - no switchport mode trunk
          - no channel-group 34

          - ip address 172.16.200.13/30

      when: ansible_network_os == 'eos'

    - name: Configuration Routeur BGP
      eos_config:
        lines:
          - configure

          - router bgp 65000
          - router-id 172.16.0.1
          - maximum-paths 4 ecmp 4
          - neighbor 172.16.200.2 remote-as 65001
          - neighbor 172.16.200.2 send-community extended
          - neighbor 172.16.200.2 maximum-routes 12000
          - neighbor 172.16.200.6 remote-as 65001
          - neighbor 172.16.200.6 send-community extended
          - neighbor 172.16.200.6 maximum-routes 12000
          - neighbor 172.16.200.10 remote-as 65002
          - neighbor 172.16.200.10 send-community extended
          - neighbor 172.16.200.10 maximum-routes 12000
          - neighbor 172.16.200.14 remote-as 65002
          - neighbor 172.16.200.14 send-community extended
          - neighbor 172.16.200.14 maximum-routes 12000
          - network 172.16.0.1/32



      when: ansible_network_os == 'eos'


