---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:


    - name: Configuration Interface Loopback0
      eos_config:
        lines:
          - configure

          - ip routing

          - interface loopback 0
          - ip address 172.16.0.3/32

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 5
      eos_config:
        lines:
          - configure

          - interface Ethernet 5
          - no switchport
          - no switchport mode trunk
          - no channel-group 56

          - ip address 172.16.200.33/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - no switchport
          - no switchport mode trunk
          - no channel-group 56
          - ip address 172.16.200.37/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 7
      eos_config:
        lines:
          - configure

          - interface Ethernet 7
          - no switchport
          - no switchport mode trunk
          - no channel-group 78
          - ip address 172.16.200.41/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 8
      eos_config:
        lines:
          - configure

          - interface Ethernet 8
          - no switchport
          - no switchport mode trunk
          - no channel-group 78
          - ip address 172.16.200.45/30

      when: ansible_network_os == 'eos'

    - name: Configuration Routeur BGP
      eos_config:
        lines:
          - configure

          - router bgp 65003
          - router-id 172.16.0.3
          - maximum-paths 4 ecmp 4
          - neighbor 172.16.200.34 remote-as 65004
          - neighbor 172.16.200.34 send-community extended
          - neighbor 172.16.200.34 maximum-routes 12000
          - neighbor 172.16.200.38 remote-as 65004
          - neighbor 172.16.200.38 send-community extended
          - neighbor 172.16.200.38 maximum-routes 12000
          - neighbor 172.16.200.42 remote-as 65005
          - neighbor 172.16.200.42 send-community extended
          - neighbor 172.16.200.42 maximum-routes 12000
          - neighbor 172.16.200.46 remote-as 65005
          - neighbor 172.16.200.46 send-community extended
          - neighbor 172.16.200.46 maximum-routes 12000
          - network 172.16.0.3/32



      when: ansible_network_os == 'eos'


