---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:


    - name: Configuration Interface Loopback0
      eos_config:
        lines:
          - configure

          - ip routing

          - interface loopback 0
          - ip address 172.16.0.11/32

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 8
      eos_config:
        lines:
          - configure



          - interface Ethernet 8
          - no switchport
          - no switchport mode trunk
          - no channel-group 12 

          - ip address 172.16.200.2/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 5
      eos_config:
        lines:
          - configure

          - interface Ethernet 5
          - no switchport
          - no switchport mode trunk
          - no channel-group 12 

          - ip address 172.16.200.18/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Vlan 3
      eos_config:
        lines:
          - configure

          - interface vlan3
          - ip address 172.16.115.2/24
          - ip virtual-router address 172.16.115.1

      when: ansible_network_os == 'eos'

    - name: Configuration MAC virtual routeur
      eos_config:
        lines:
          - configure

          - ip virtual-router mac-address 00:1c:73:00:00:12

      when: ansible_network_os == 'eos'


    - name: Configuration Routeur BGP
      eos_config:
        lines:
          - configure

          - router bgp 65001
          - router-id 172.16.0.11
          - maximum-paths 4 ecmp 4
          - neighbor 172.16.12.2 remote-as 65001
          - neighbor 172.16.12.2 next-hop-self
          - neighbor 172.16.200.1 remote-as 65000
          # - neighbor 172.16.200.1 send-community extended
          - neighbor 172.16.200.1 maximum-routes 12000
          - neighbor 172.16.200.17 remote-as 65000
          # - neighbor 172.16.200.17 send-community extended
          - neighbor 172.16.200.17 maximum-routes 12000
          - network 172.16.0.11/32
          - network 172.16.115.0/24



      when: ansible_network_os == 'eos'


