---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"
    mlag_peer_link_description: "MLAG PEER LINK - LEAF-5"

  tasks:
    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - description "{{ mlag_peer_link_description }}"
          - channel-group 10 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 4
      eos_config:
        lines:
          - configure

          - interface Ethernet 4
          - description "{{ mlag_peer_link_description }}"
          - channel-group 10 mode active

      when: ansible_network_os == 'eos'

    - name: Configuration Port Channel 10
      eos_config:
        lines:
          - configure

          - interface port-channel 10
          - description "{{ mlag_peer_link_description }}"
          - switchport mode trunk
          - switchport trunk group MLAGPEER
          - no spanning-tree vlan-id 4094

      when: ansible_network_os == 'eos'
    - name: Configure IP addresses on Port Channel 10 LEAF-5
      eos_config:
        lines:
          - configure
          - interface vlan 4094
          - description MLAG PEER LINK Leaf5-Side
          - ip address 172.16.3.2/24

      when: ansible_network_os == 'eos'
