---
- name: Run commands on remote cEOS-lab device
  hosts: arista
  connection: httpapi
  gather_facts: no
  vars:
    ansible_python_interpreter: "python"

  tasks:


    - name: Configuration Interface Loopback0
      eos_config:
        lines:
          - configure

          - ip routing

          - interface loopback 0
          - ip address 172.16.0.12/32

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 7
      eos_config:
        lines:
          - configure



          - interface Ethernet 7
          - no switchport
          - no switchport mode trunk
          - no channel-group 12 

          - ip address 172.16.200.6/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Ethernet 6
      eos_config:
        lines:
          - configure

          - interface Ethernet 6
          - no switchport
          - no switchport mode trunk
          - no channel-group 12 

          - ip address 172.16.200.22/30

      when: ansible_network_os == 'eos'

    - name: Configuration Interface Vlan 3
      eos_config:
        lines:
          - configure

          - interface vlan3
          - ip address 172.16.115.3/24
          - ip virtual-router address 172.16.115.1

      when: ansible_network_os == 'eos'

    - name: Configuration MAC virtual routeur
      eos_config:
        lines:
          - configure

          - ip virtual-router mac-address 00:1c:73:00:00:12

      when: ansible_network_os == 'eos'


    - name: Configuration Routeur BGP
      eos_config:
        lines:
          - configure

          - router bgp 65001
          - router-id 172.16.0.12
          - maximum-paths 4 ecmp 4
          - neighbor 172.16.12.1 remote-as 65001
          - neighbor 172.16.12.1 next-hop-self
          - neighbor 172.16.200.5 remote-as 65000
          - neighbor 172.16.200.5 maximum-routes 12000
          - neighbor 172.16.200.21 remote-as 65000
          - neighbor 172.16.200.21 maximum-routes 12000
          - network 172.16.0.12/32
          - network 172.16.1.12/32
          - network 172.16.115.0/24



      when: ansible_network_os == 'eos'


